version: '3.7'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challenge_db
      MYSQL_USER: challenge
      MYSQL_PASSWORD: challenge
    ports:
      - 3306:3306
    volumes:
      - ./database/schemas/:/var/lib/mysql
    networks:
      - challenge
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www/
      - ./backend/public:/var/www/html
    networks:
      - challenge
    depends_on:
      - db
  frontend:
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    #   target: develop-stage
    # ports:
    #   - 3000:3000
    # volumes:
    #   - ./frontend:/frontend
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    # networks:
    #   - challenge
    # command: /bin/sh -c "npm run dev"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - challenge
    command: /bin/sh -c "npm install && npm run dev"
volumes:
  backend:
  database:
  frontend:
networks:
  challenge:

